#!/usr/bin/env node
// Regression sweep for the generator. Generates workouts across every
// combination of environment, strength block and format, and writes what came
// out to out/smoke-report.md.
//
// The output is random, so "the workouts still look plausible" is not evidence
// that a change was safe. This produces numbers instead: run it, commit the
// report, change the model, run it again, and read the diff.
//
// Usage:
//   npm run smoke                 # default 400 samples per cell
//   SAMPLES=2000 npm run smoke    # tighter numbers, slower
//   SEED=7 npm run smoke          # different deterministic run
//   OUT=out/after.md npm run smoke

import fs from "node:fs";
import path from "node:path";
import { AXES } from "../src/moves.js";
import { FORMATS, STRENGTH } from "../src/formats.js";
import { generate, sessionLoad } from "../src/generator.js";

const SAMPLES = Number(process.env.SAMPLES || 400);
const SEED = Number(process.env.SEED || 1);
const OUT = process.env.OUT || "out/smoke-report.md";
const ENVS = ["gym", "parque", "casa"];

// The generator calls Math.random directly. Swap in a seeded PRNG so two runs
// of the same code produce identical reports and a diff means a real change.
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
Math.random = mulberry32(SEED);

const conditioning = (c) => sessionLoad(c).conditioning;

const stat = () => ({ n: 0, sum: 0, min: Infinity, max: -Infinity, vals: [] });
const push = (s, v) => { s.n++; s.sum += v; s.min = Math.min(s.min, v); s.max = Math.max(s.max, v); s.vals.push(v); };
const mean = (s) => (s.n ? s.sum / s.n : 0);
function pct(s, p) {
  if (!s.n) return 0;
  const v = [...s.vals].sort((a, b) => a - b);
  return v[Math.min(v.length - 1, Math.floor(p * v.length))];
}

const byFormat = {};
const byEnv = {};
const byStrength = {};
const axisAcc = Object.fromEntries(AXES.map((a) => [a, stat()]));
const warnCount = {};
const moveCount = new Map();
let total = 0, nulls = 0, faultyCount = 0;

for (const env of ENVS) {
  byEnv[env] ||= { load: stat(), cond: stat(), items: stat(), faults: stat() };
  for (const st of STRENGTH) {
    byStrength[st.id] ||= { load: stat(), cond: stat(), items: stat(), faults: stat() };
    for (let i = 0; i < SAMPLES; i++) {
      const c = generate(env, st.id);
      total++;
      if (!c) { nulls++; continue; }

      const load = Math.round(sessionLoad(c).total);
      const f = c.faults || [];
      const hard = f.filter((x) => x.hard).length;
      if (hard > 0) faultyCount++;

      byFormat[c.fmt.id] ||= { load: stat(), cond: stat(), items: stat(), faults: stat() };
      for (const bucket of [byFormat[c.fmt.id], byEnv[env], byStrength[st.id]]) {
        push(bucket.load, load);
        push(bucket.cond, Math.round(conditioning(c)));
        push(bucket.items, c.items.length);
        push(bucket.faults, hard);
      }

      const sum = AXES.reduce((s, a) => s + c.vec[a], 0) || 1;
      for (const a of AXES) push(axisAcc[a], c.vec[a] / sum);

      for (const x of f) {
        const k = x.k + (x.a ? `:${x.a}` : "");
        warnCount[k] = (warnCount[k] || 0) + 1;
      }
      for (const it of c.items) moveCount.set(it.move.id, (moveCount.get(it.move.id) || 0) + 1);
    }
  }
}

const n1 = (x) => x.toFixed(1);
const n3 = (x) => x.toFixed(3);
const L = [];

L.push("# Smoke report");
L.push("");
L.push(`Generated by \`scripts/smoke.js\`. Regenerated, never hand-edited.`);
L.push("");
L.push(`- samples per environment x strength block: **${SAMPLES}**`);
L.push(`- seed: **${SEED}** (deterministic; the same code gives the same report)`);
L.push(`- workouts generated: **${total}**, of which **${nulls}** returned null`);
L.push(`- carrying at least one hard fault: **${faultyCount}** (${n1((faultyCount / total) * 100)}%)`);
L.push("");

L.push("## Session load by format");
L.push("");
L.push("Load in points, where 20 points is about one hard minute of work.");
L.push("");
L.push("`Cond` is the conditioning piece alone. `Load` adds the strength block.");
L.push("");
L.push("| Format | Share | Cond mean | Cond p10 | Cond p90 | Load mean | Load min | Load max | Items | Hard faults |");
L.push("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|");
for (const f of FORMATS) {
  const b = byFormat[f.id];
  if (!b) { L.push(`| ${f.id} | 0% | | | | | | | | |`); continue; }
  L.push(`| ${f.id} | ${n1((b.load.n / (total - nulls)) * 100)}% | ${n1(mean(b.cond))} | ${pct(b.cond, 0.1)} | ${pct(b.cond, 0.9)} | ${n1(mean(b.load))} | ${b.load.min} | ${b.load.max} | ${n1(mean(b.items))} | ${n3(mean(b.faults))} |`);
}
L.push("");

L.push("## Session load by environment");
L.push("");
L.push("| Environment | Load mean | p10 | p90 | Items | Hard faults |");
L.push("|---|---:|---:|---:|---:|---:|");
for (const e of ENVS) {
  const b = byEnv[e];
  L.push(`| ${e} | ${n1(mean(b.load))} | ${pct(b.load, 0.1)} | ${pct(b.load, 0.9)} | ${n1(mean(b.items))} | ${n3(mean(b.faults))} |`);
}
L.push("");

L.push("## Session load by strength block");
L.push("");
L.push("| Strength | Load mean | p10 | p90 | Items | Hard faults |");
L.push("|---|---:|---:|---:|---:|---:|");
for (const st of STRENGTH) {
  const b = byStrength[st.id];
  L.push(`| ${st.id} | ${n1(mean(b.load))} | ${pct(b.load, 0.1)} | ${pct(b.load, 0.9)} | ${n1(mean(b.items))} | ${n3(mean(b.faults))} |`);
}
L.push("");

L.push("## Axis shares");
L.push("");
L.push("Share of total effort taken by each axis, averaged over every workout.");
L.push("");
L.push("| Axis | Mean | p10 | p90 |");
L.push("|---|---:|---:|---:|");
for (const a of AXES) {
  const s = axisAcc[a];
  L.push(`| ${a} | ${n3(mean(s))} | ${n3(pct(s, 0.1))} | ${n3(pct(s, 0.9))} |`);
}
L.push("");

L.push("## Warnings raised");
L.push("");
L.push("| Warning | Count | Per workout |");
L.push("|---|---:|---:|");
for (const [k, v] of Object.entries(warnCount).sort((a, b) => b[1] - a[1])) {
  L.push(`| ${k} | ${v} | ${n3(v / (total - nulls))} |`);
}
if (!Object.keys(warnCount).length) L.push("| none | 0 | 0.000 |");
L.push("");

L.push("## Movement frequency");
L.push("");
L.push("Movements that never appear are unreachable: check their `env` and `pat`.");
L.push("");
const used = [...moveCount.entries()].sort((a, b) => b[1] - a[1]);
const slots = used.reduce((s, [, v]) => s + v, 0);
L.push("| Movement | Count | Share of slots |");
L.push("|---|---:|---:|");
for (const [id, v] of used) L.push(`| ${id} | ${v} | ${n3(v / slots)} |`);
L.push("");

const report = L.join("\n") + "\n";
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, report);

console.log(`Wrote ${OUT}`);
console.log(`  ${total} workouts, ${nulls} null, ${n1((faultyCount / total) * 100)}% carrying a hard fault`);
for (const f of FORMATS) {
  const b = byFormat[f.id];
  if (b) console.log(`  ${f.id.padEnd(10)} cond mean ${n1(mean(b.cond)).padStart(6)}   session mean ${n1(mean(b.load)).padStart(6)}`);
}
